# Generated by Django 2.2.5 on 2019-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190930_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spendp_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spendpr_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
