# Generated by Django 2.2.5 on 2019-09-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_address', models.CharField(max_length=255)),
                ('lending_address', models.CharField(max_length=255)),
                ('borrower_nin_hash', models.CharField(max_length=255)),
                ('pay_id', models.CharField(max_length=255)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expected_payment_date', models.DateTimeField()),
                ('loan_status', models.IntegerField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField()),
                ('actual_payment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paying_address', models.CharField(max_length=255)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('installment_number', models.IntegerField()),
                ('repayment_penalty', models.BooleanField(default=False)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan', to='loans.Loans')),
            ],
        ),
    ]
