# Generated by Django 2.2.5 on 2019-10-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loans_expected_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
