# Generated by Django 2.2.5 on 2019-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20190918_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='actual_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
