# Generated by Django 2.2.5 on 2019-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20190918_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('hashed_nin', models.CharField(max_length=64)),
                ('bnu_address', models.CharField(max_length=108)),
                ('physical_address', models.CharField(max_length=255)),
                ('user_number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('refferal_id', models.CharField(max_length=6)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='loanpayments',
            name='paying_address',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='loans',
            name='borrower_address',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='loans',
            name='borrower_nin_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='lending_address',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='pay_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
