# Generated by Django 2.2.5 on 2019-10-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20191010_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayments',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='outstanding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
