# Generated by Django 2.2.5 on 2019-10-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20191014_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_owner_address', models.CharField(max_length=108)),
                ('credit_refferal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('network_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('loan_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_repayment_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_number_of_installments', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('loan_completion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('late_payment_penalties', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_computed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
