# Generated by Django 2.2.5 on 2019-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_creditscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_owner_address', models.CharField(max_length=108)),
                ('number_of_loans_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_lent_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_computed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
