# Generated by Django 2.2.5 on 2019-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20190925_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_nin',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
