# Generated by Django 2.2.5 on 2019-11-20 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0007_lendingrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_title', models.CharField(max_length=255)),
                ('metric_percentage_contribution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metric_description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditScoreCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_score', models.IntegerField()),
                ('date_computed', models.DateTimeField(auto_now_add=True)),
                ('related_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_owner', to=settings.AUTH_USER_MODEL)),
                ('related_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_id', to='loans.ScoreMetric')),
            ],
        ),
    ]
