# Generated by Django 2.2.5 on 2019-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_creditscorecalculation_scoremetric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditScores',
        ),
        migrations.AddField(
            model_name='scoremetric',
            name='metric_classification',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
